nmHoistingLimits: workspaces

nodeLinker: node-modules

packageExtensions:
  debug@*:
    dependencies:
      supports-color: '*'
  local-pkg@*:
    dependencies:
      '@vitest/coverage-c8': '*'
  vite@*:
    dependencies:
      supports-color: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

pnpEnableEsmLoader: true

pnpMode: loose

supportedArchitectures:
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-3.4.1.cjs
